### ISSUE TITLE
Do not fail on superfluous translations

### ISSUE THREAD

**Issue by siebrand** [wikimedia/grunt-banana-checker#37]
Superfluous translations are not in the way, and they are a lot of work to remove from many files. Please do not fail on superfluous translations, not in qqq, and not in any other language.

Refs:
* https://phabricator.wikimedia.org/T112854
* https://gerrit.wikimedia.org/r/#/c/241091/ / https://integration.wikimedia.org/ci/job/npm/27659/console

06:14:04 Running "banana:Metrolook" (banana) task
06:14:04 >> The "bn" translation has 1 unused translation:
06:14:04 >> The translation of "skinname-metrolook" is unused.
06:14:04 >> The "jbo" translation has 1 unused translation:
06:14:04 >> The translation of "skinname-metrolook" is unused.
06:14:04 >> The "ko" translation has 1 unused translation:
06:14:04 >> The translation of "skinname-metrolook" is unused.
06:14:04 >> The "mk" translation has 1 unused translation:
06:14:04 >> The translation of "skinname-metrolook" is unused.

**Comment by Krinkle** [comment]
I guess because they are automatically removed in the next sync? (and the practice for code change commits is to only remove them from the primary file, right?)

In that case, this has already been addressed in 71880f9b7d. The next release will have this option disabled by default. In the meantime you can set `disallowUnusedTranslations: false` in Gruntfile.
