### ISSUE TITLE
Don't try to check for bananas in editor swap files

### ISSUE THREAD

**Issue by anomiex** [wikimedia/grunt-banana-checker#46]
If I have one of the i18n json files open in vim, the banana checker apparently tries to check the swap file (e.g. ".en.json.swp") for bananas and fails badly:

> Running "banana:core" (banana) task
> Warning: Cannot read property '1' of null Use --force to continue.

It should ignore these files.

**Comment by Krinkle** [comment]
Thank you for finding and reporting this issue, @anomiex.

It appears this is caused by the regex at https://github.com/wikimedia/grunt-banana-checker/blob/84922134a2ac637d1f1ee83dc62f55c59bca078c/tasks/banana.js#L98. It should be anchored to the end of the filename instead of allowing open-ended matches. E.g. `/.*.json$/` instead of `/.*.json/`. It should also escape the second dot.
